### ISSUE TITLE
Proxy error: Could not proxy request ... ECONNRESET

### ISSUE THREAD

**Issue by Mukrosz** [cloud-carbon-footprint/cloud-carbon-footprint#1103]
I am trying to start the app `yarn start` but get Proxy error ... ECONNRESET error as follows:

```
user@myccfserver:/cloud-carbon-footprint> DANGEROUSLY_DISABLE_HOST_CHECK=true yarn start
[1] [INFO] 16:13:36 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.8.2, typescript ver. 4.7.4)
[0] Attempting to bind to HOST environment variable: myccfserver
[0] If this was unintentional, check that you haven't mistakenly set it in your shell.
[0] Learn more here: https://cra.link/advanced-config
[0]
[0] (node:8800) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[0] (Use `node16 --trace-deprecation ...` to show where the warning was created)
[0] (node:8800) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[0] Starting the development server...
[0]
[0] Compiled successfully!
[0]
[0] You can now view @cloud-carbon-footprint/client in the browser.
[0]
[0]   http://myccfserver:3000
[0]
[0] Note that the development build is not optimized.
[0] To create a production build, use npm run build.
[0]
[0] webpack compiled successfully
[0] Files successfully emitted, waiting for typecheck results...
[0] Issues checking in progress...
[0] No issues found.
[1] 2023-03-29T22:14:07.823Z [server] info: Cloud Carbon Footprint Server listening at http://localhost:4000
[1] 2023-03-29T22:15:30.865Z [api] info: Regions emissions factors API request started
[1] 2023-03-29T22:15:30.874Z [api] info: Footprint API request started.
[1] 2023-03-29T22:15:30.879Z [Cache] info: Using local cache file...
[1] 2023-03-29T22:15:30.890Z [Cache] info: Ignoring cache...
[1] 2023-03-29T22:15:30.903Z [App] info: Starting GCP Estimations
[1] 2023-03-29T22:15:32.487Z [BillingExportTable] info: Getting Big Query Results
[0] Proxy error: Could not proxy request /api/footprint?start=2021-01-01&end=2022-06-01&ignoreCache=true&groupBy=day&limit=50000&skip=0 from myccfserver.company.com:3000 to http://localhost:4000.
[0] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
[0]
[1] 2023-03-29T23:43:27.675Z [BillingExportTable] info: Mapping over Usage Rows
[1]
[1] <--- Last few GCs --->
[1]
[1] [1830:0x55aec8935c80]  1183770 ms: Mark-sweep 1902.0 (2080.7) -> 1886.3 (2081.2) MB, 3686.2 / 0.0 ms  (average mu = 0.117, current mu = 0.013) allocation failure scavenge might not succeed
[1] [1830:0x55aec8935c80]  1187963 ms: Mark-sweep 1902.2 (2081.2) -> 1886.7 (2081.4) MB, 4145.8 / 0.0 ms  (average mu = 0.064, current mu = 0.011) allocation failure scavenge might not succeed
[1]
[1]
[1] <--- JS stacktrace --->
[1]
[1] FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
[1]  1: 0x55aec6572000 node::Abort() [/usr/bin/node16]
[1]  2: 0x55aec6572c39 node::OOMErrorHandler(char const*, bool) [/usr/bin/node16]
[1]  3: 0x55aec6757bc0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node16]
[1]  4: 0x55aec6757e42 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node16]
[1]  5: 0x55aec6903915  [/usr/bin/node16]
[1]  6: 0x55aec6903a1c v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/bin/node16]
[1]  7: 0x55aec6916816 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/bin/node16]
[1]  8: 0x55aec6917105 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node16]
[1]  9: 0x55aec6919f19 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node16]
[1] 10: 0x55aec6919fa5 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node16]
[1] 11: 0x55aec68de293 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/bin/node16]
[1] 12: 0x55aec6c19258 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node16]
[1] 13: 0x55aec6fcb3f9  [/usr/bin/node16]
[1] yarn start-api exited with code 0
```
Note that there is also the `JavaScript heap out of memory` error. I have 16GBs of memory. At the time of the crash, only around 40% of memory is consumed.

OS: SLES15
Browser: Chrome
Any ideas?

**Comment by 4upz** [comment]
Hi @Mukrosz Thanks for trying out CCF and for opening this issue! 

For the proxy error, you may want to check that the proxy configured in your `packages/client/package.json` file matches the url that the API is using -- especially if you're using a custom host for the client. If everything does match up, then it's a matter of having the API started before the client starts so that it can successfully find the proxied connection. In the case that the client starts before the API, you should be able to refresh the client page after the API finishes starting and the error will go away.

As for the Javascript Heap out of memory error, this is most likely occurring if you're dealing with a huge amount of usage being calculated at one time. You could increase the allowed memory for NodeJS as detailed in this [StackOverflow issue](https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas). If you still find it difficult to stay under the memory limit with your usage size, we recommend exploring some caching options such as [MongoDB](https://www.cloudcarbonfootprint.org/docs/data-persistence-and-caching#mongodb-storage) or reducing the configured time range of your request.

Let me know if that helps!

**Comment by Mukrosz** [comment]
Thank you very much @4upz .
Strangely the proxy error was related to the memory allocation for NodeJS.
I have doubled the memory for NodeJS as per your above suggestion and that got me over the finish line (thank you!):
```
[1] 2023-03-31T19:54:16.400Z [server] info: Cloud Carbon Footprint Server listening at http://localhost:4000
[1] 2023-03-31T19:54:59.844Z [api] info: Footprint API request started.
[1] 2023-03-31T19:54:59.869Z [Cache] info: Using local cache file...
[1] 2023-03-31T19:54:59.875Z [api] info: Regions emissions factors API request started
[1] 2023-03-31T19:54:59.906Z [Cache] info: Ignoring cache...
[1] 2023-03-31T19:54:59.932Z [App] info: Starting GCP Estimations
[1] 2023-03-31T19:55:02.571Z [BillingExportTable] info: Getting Big Query Results
[1] 2023-03-31T20:03:58.914Z [BillingExportTable] info: Mapping over Usage Rows
[1] 2023-03-31T20:11:30.728Z [App] info: Finished GCP Estimations
[1] 2023-03-31T20:15:29.538Z [api] info: Regions emissions factors API request started
```

As per my [previous issue](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/1071) I cannot figure out how to start the app without the use of `DANGEROUSLY_DISABLE_HOST_CHECK=true`.
Any suggestions on that font?
I thought it was specific to `yarn start-with-mock-data` but I am now using real data from GCP.

**Comment by Mukrosz** [comment]
I've also noticed that the estimates are only good per browser session? If I were to refresh my browser, the collection takes place over again (10 - 15 minutes). Similarly, if another person opens the browser page, the loading process repeats.
Is that intentional behavior? I see `/cloud-carbon-footprint/packages/api/estimates.cache.day.json` file as per [caching doc](https://www.cloudcarbonfootprint.org/docs/data-persistence-and-caching) but it is tiny and several week old.
Thanks!

**Comment by 4upz** [comment]
@Mukrosz   No problem, glad that worked! 

As for the host check, it's still persisting because it's a webpack configuration that Create-React-App uses under the hood in general. it looks like you're using it as temporary environment variable but just within the `yarn start` command, which isn't necessarily a bad thing. However, you should be able to permanently set this in the `.env` file within the root of your client as `DANGEROUSLY_DISABLE_HOST_CHECK=true`. If that doesn't work, you may have to make a new file in the root of your client called `.env.development.local` for webpack to find it. 

Also, the estimates are refreshing per session because you seem to have cache ignored as shown in the following line of the last log you sent:
```
[1] 2023-03-31T19:54:59.906Z [Cache] info: Ignoring cache...
```
This means that any saved estimates are ignored and any new ones are not persisted, thus prompting them to be fetched again per session. That's also why you see the `estimates.cache.day.json` file, which isn't being used nor updated. You would need to enable the cache by removing `REACT_APP_DISABLE_CACHE=true` in your client's `.env` file if you have it set, or by explicitly setting it to false using the same variable. 

I hope that helps!

**Comment by Mukrosz** [comment]
@4upz Yet again, thank you! Both of these suggestions helped me. `REACT_APP_DISABLE_CACHE=true` was indeed set. I have not modified that .env file which is probably why.
Interesting that with the cache enabled, the front end app page just goes into a Timeout error after about a minute but the server was busy.
Sadly after about 40 minutes it spat an error and quit:(  (I was so hopeful!)
```
[1] 2023-03-31T22:21:35.926Z [server] info: Cloud Carbon Footprint Server listening at http://localhost:4000
[1] 2023-03-31T22:22:35.079Z [api] info: Regions emissions factors API request started
[1] 2023-03-31T22:22:35.090Z [api] info: Footprint API request started.
[1] 2023-03-31T22:22:35.096Z [Cache] info: Using local cache file...
[1] 2023-03-31T22:22:35.127Z [App] info: Starting GCP Estimations
[1] 2023-03-31T22:22:36.487Z [BillingExportTable] info: Getting Big Query Results
[1] 2023-03-31T22:30:43.745Z [api] info: Regions emissions factors API request started
[1] 2023-03-31T22:30:43.760Z [api] info: Footprint API request started.
[1] 2023-03-31T22:30:43.762Z [Cache] info: Using local cache file...
[1] 2023-03-31T22:30:43.784Z [App] info: Starting GCP Estimations
[1] 2023-03-31T22:30:45.377Z [BillingExportTable] info: Getting Big Query Results
[1] 2023-03-31T22:39:24.792Z [BillingExportTable] info: Mapping over Usage Rows
[1] 2023-03-31T22:52:16.271Z [App] info: Finished GCP Estimations
[1] 2023-03-31T22:52:16.848Z [Cache] info: Setting new estimates to cache...
[1] 2023-03-31T22:59:30.152Z [BillingExportTable] info: Mapping over Usage Rows

[1] 2023-03-31T23:14:12.346Z [App] info: Finished GCP Estimations
[1] 2023-03-31T23:14:12.836Z [Cache] info: Setting new estimates to cache...
[1] 2023-03-31T23:14:12.865Z [api] info: Regions emissions factors API request started
[1] 2023-03-31T23:14:12.878Z [api] info: Footprint API request started.
[1] 2023-03-31T23:14:12.881Z [Cache] info: Using local cache file...
[1] 2023-03-31T23:14:12.887Z [api] info: Regions emissions factors API request started
[1] 2023-03-31T23:14:12.895Z [api] info: Footprint API request started.
[1] 2023-03-31T23:14:12.896Z [Cache] info: Using local cache file...
[1] 2023-03-31T23:14:57.610Z [api] error: Unable to process footprint request.RangeError: Invalid string length
[1]     at JSON.stringify (<anonymous>)
[1]     at stringify (/cloud-carbon-footprint/node_modules/express/lib/response.js:1150:12)
[1]     at ServerResponse.json (/cloud-carbon-footprint/node_modules/express/lib/response.js:271:14)
[1]     at FootprintApiMiddleware (/cloud-carbon-footprint/packages/api/src/api.ts:64:9)
[1]     at runMicrotasks (<anonymous>)
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1] 2023-03-31T23:15:05.706Z [api] error: Unable to process footprint request.RangeError: Invalid string length
[1]     at JSON.stringify (<anonymous>)
[1]     at stringify (/cloud-carbon-footprint/node_modules/express/lib/response.js:1150:12)
[1]     at ServerResponse.json (/cloud-carbon-footprint/node_modules/express/lib/response.js:271:14)
[1]     at FootprintApiMiddleware (/cloud-carbon-footprint/packages/api/src/api.ts:64:9)
[1]     at runMicrotasks (<anonymous>)
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Mukrosz** [comment]
Update: restarting the app seem to have rejuvenated it, I was able open the browser page using the cached file. More experimentation is needed.
```
[1] 2023-03-31T23:40:49.827Z [server] info: Cloud Carbon Footprint Server listening at http://localhost:4000
[1] 2023-03-31T23:42:40.368Z [api] info: Regions emissions factors API request started
[1] 2023-03-31T23:42:40.381Z [api] info: Footprint API request started.
[1] 2023-03-31T23:42:40.386Z [Cache] info: Using local cache file...
[1] 2023-03-31T23:43:22.230Z [api] info: Footprint API request started.
[1] 2023-03-31T23:43:22.234Z [Cache] info: Using local cache file...
[1] 2023-03-31T23:51:04.709Z [api] info: Regions emissions factors API request started
```
Now I need to see if I can systemd daemonize this app.

**Comment by 4upz** [comment]
@Mukrosz Awesome, happy to see that that things are going a bit more smoothly! I have seen some users manage to run CCF as a background service using a `.service` file. However, I don't have enough personal experience with it to provide ample guidance -- but would love to hear about your process if you manage to solve it! Since there are no actionable steps on our side, I'll go ahead and close this issue. But feel free to still drop a message if you have more questions/issues!

**Comment by gagan4580** [comment]
i posted a similar issue 5 days ago, please check @4upz
