### ISSUE TITLE
date is not in a recognized RFC2822 or ISO format

### ISSUE THREAD

**Issue by davidguardiola** [cloud-carbon-footprint/cloud-carbon-footprint#1264]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Ubuntu 18.04
Carbon Footprint latest version

Appear this error:
`[1] 2023-10-24T14:15:18.324Z [api] error: Unable to process footprint request.EstimationRequestValidationError: Start date is not in a recognized RFC2822 or ISO format, End date is not in a recognized RFC2822 or ISO format
[1]     at new EstimationRequestValidationError (/home/ec2-user/cloud-carbon-footprint/packages/common/src/Errors.ts:13:5)
[1]     at validate (/home/ec2-user/cloud-carbon-footprint/packages/app/src/CreateValidRequest.ts:178:11)
[1]     at createValidFootprintRequest (/home/ec2-user/cloud-carbon-footprint/packages/app/src/CreateValidRequest.ts:280:3)
[1]     at /home/ec2-user/cloud-carbon-footprint/packages/api/src/api.ts:60:58
[1]     at step (/home/ec2-user/cloud-carbon-footprint/packages/api/src/api.ts:33:23)
[1]     at Object.next (/home/ec2-user/cloud-carbon-footprint/packages/api/src/api.ts:14:53)
[1]     at /home/ec2-user/cloud-carbon-footprint/packages/api/src/api.ts:8:71
[1]     at new Promise (<anonymous>)
[1]     at __awaiter (/home/ec2-user/cloud-carbon-footprint/packages/api/src/api.ts:4:12)
[1]     at FootprintApiMiddleware (/home/ec2-user/cloud-carbon-footprint/packages/api/src/api.ts:49:12)
[1]     at Layer.handle [as handle_request] (/home/ec2-user/cloud-carbon-footprint/node_modules/express/lib/router/layer.js:95:5)
[1]     at next (/home/ec2-user/cloud-carbon-footprint/node_modules/express/lib/router/route.js:144:13)
[1]     at Route.dispatch (/home/ec2-user/cloud-carbon-footprint/node_modules/express/lib/router/route.js:114:3)
[1]     at Layer.handle [as handle_request] (/home/ec2-user/cloud-carbon-footprint/node_modules/express/lib/router/layer.js:95:5)
[1]     at /home/ec2-user/cloud-carbon-footprint/node_modules/express/lib/router/index.js:284:15
[1]     at Function.process_params (/home/ec2-user/cloud-carbon-footprint/node_modules/express/lib/router/index.js:346:12)`

### Additional Information

© 2021 Thoughtworks, Inc.

**Comment by 4upz** [comment]
Hi @davidguardiola, thanks for opening this issue. This seems to be a normal validation error logged by the API, usually when an improper value is given for the startDate.

Can you provide some additional details, such as the value you tried to provide to the parameter?
