### ISSUE TITLE
API is not starting up after deploying ccf on AWS

### ISSUE THREAD

**Issue by shuknk8s** [cloud-carbon-footprint/cloud-carbon-footprint#1384]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:** Amazon Linux 2
  -  Amazon Linux 2
- **Browser:**
  -  Chrome - latest 

### Expected Behavior

yarn start-api throws the following error 

arn start-api
[INFO] 22:19:08 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.8.2, typescript ver. 4.7.4)
SyntaxError: Unexpected token ? in JSON at position 35
    at JSON.parse (<anonymous>)
    at getConfig (/home/ec2-user/cloud-carbon-footprint/packages/common/src/Config.ts:231:20)
    at Object.<anonymous> (/home/ec2-user/cloud-carbon-footprint/packages/common/src/ConfigLoader.ts:7:35)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._compile (/home/ec2-user/cloud-carbon-footprint/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-5843073353933581.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-5843073353933581.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-5843073353933581.js:71:20)
    at Object.nodeDevHook [as .ts] (/home/ec2-user/cloud-carbon-footprint/node_modules/ts-node-dev/lib/hook.js:63:13)
[ERROR] 22:19:26 SyntaxError: Unexpected token ? in JSON at position 35

### Actual Behavior
Should have the api server up and running 

### To Reproduce

Deploy ccf on aws using the terraform/aws script 
tail the log as per doc 

### Additional Information

© 2021 Thoughtworks, Inc.

**Comment by shuknk8s** [comment]
Not sure if this has been reported earlier or I am committing some silly mistakes

**Comment by shuknk8s** [comment]
here is the ami id selected in use-east-1 for spinning up the ec2 instance - "ami-06b21ccaeff8cd686" # Amazon Linux AMI 2.

**Comment by shuknk8s** [comment]
Following up since this a vanilla deployment of CCF on AWS and should work as per documentation and scripts provided.
