### ISSUE TITLE
AWS concurrency limit exceeded on initial load

### ISSUE THREAD

**Issue by pwithnall** [cloud-carbon-footprint/cloud-carbon-footprint#261]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](../blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - `docker-compose`
- **Browser:** 
  - Firefox

### Expected Behavior

On initial load of CCF, it should load the AWS usage data (as configured). If the AWS API returns a `request.LimitExceededException`, CCF should back off its level of parallelisation so that it has fewer queries in flight at once.

### Actual Behavior

I am trying to use CCF with `AWS_USE_BILLING_DATA` unset (i.e. false), but with `AWS_ACCOUNTS` set. I believe this is the ‘higher accuracy’ approach.

The initial load loaded the header bar of the app, then gave an error 500. The server logs gave the following exception:
```
api_1     | 2021-05-06T15:35:09.761Z [api] error: Unable to process footprint request.LimitExceededException: Account maximum query concurrency limit of [10] reached. (Service: AWSLogs; Status Code: 400; Error Code: LimitExceededException; Request ID: 72da7e69-990c-40f0-8c9f-3295ff3b9c84; Proxy: null)
api_1     |     at Request.extractError (/usr/src/app/node_modules/aws-sdk/lib/protocol/json.js:52:27)
api_1     |     at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
api_1     |     at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
api_1     |     at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/request.js:688:14)
api_1     |     at Request.transition (/usr/src/app/node_modules/aws-sdk/lib/request.js:22:10)
api_1     |     at AcceptorStateMachine.runTo (/usr/src/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
api_1     |     at /usr/src/app/node_modules/aws-sdk/lib/state_machine.js:26:10
api_1     |     at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:38:9)
api_1     |     at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:690:12)
api_1     |     at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

I have requested that Amazon increase our query parallelisation limit, but that takes time, and it would be nice for CCF to work regardless of the limit, even if that means loading more slowly.

### To Reproduce

Run CCF using `docker-compose`, with the following configuration:
 * `AWS_USE_BILLING_DATA=` (i.e. unset)
 * `AWS_ACCOUNTS` set and non-empty
 * GCP and Azure disabled

**Comment by ccasher** [comment]
Thank you for creating this issue! This is something we will put into the backlog for prioritization.

**Comment by ericksod** [comment]
Hi @pwithnall!
Sorry for the delay in getting back to you. 
We were wondering, what services were you attempting to pull data for? It would be helpful to understand some specifics to debug this.
Thanks!

**Comment by pwithnall** [comment]
Just AWS (not GCP or Azure). I eventually got it running using Athena, and the services which CCF now successfully lists are:
 * AmazonEC2
 * AmazonRDS
 * AmazonS3
 * AmazonElastiCache
 * AWSELB
 * AmazonECS
 * AWSGlue
 * AmazonECR
 * AWSLambda
 * AmazonApiGateway
 * AmazonCloudWatch

**Comment by jules-ch** [comment]
Hitting this aswell
