### ISSUE TITLE
Failed to run API footprint/emissions in cost explorer approach

### ISSUE THREAD

**Issue by mattcui** [cloud-carbon-footprint/cloud-carbon-footprint#559]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  macOS 12.0.1
- **Browser:**
  Chrome

### Expected Behavior

I tried to use the [alternative approach](https://www.cloudcarbonfootprint.org/docs/alternative-data-approaches#using-cloud-usage-apis-higher-accuracy) to get the data from my AWS account, I can build application and start it successfully with my .env like:
```
AWS_TARGET_ACCOUNT_ROLE_NAME=xxx-Admin
AWS_ACCOUNTS=[{"id":"76064434xxxx","name":"assumed-role/PAT-Admin/xue.cui@nordcloud.com"}]
AWS_AUTH_MODE=default
```

```
[1] [INFO] 18:12:10 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.4.4)
[0] ℹ ｢wds｣: Project is running at http://192.168.1.5/
[0] ℹ ｢wds｣: webpack output is served from
[0] ℹ ｢wds｣: Content not from webpack is served from /Users/mattcui/myspace/src/klarity-ccf/packages/client/public
[0] ℹ ｢wds｣: 404s will fallback to /
[0] Starting the development server...
[0]
[1] 2021-11-02T10:12:14.331Z [server] info: Cloud Carbon Footprint Server listening at http://localhost:4000
[1] 2021-11-02T10:12:17.220Z [api] info: Recommendations API request started
[0] Files successfully emitted, waiting for typecheck results...
[0] Compiled successfully!
[0]
[0] You can now view @cloud-carbon-footprint/client-template in the browser.
[0]
[0]   Local:            http://localhost:3000
[0]   On Your Network:  http://192.168.1.5:3000
[0]
```

I expected console and all apis can work.

### Actual Behavior
But there reported 500 error when trying to access http://localhost:3000, from command line, I can use curl to query recommendations successfully:
```
curl -X GET http://localhost:4000/api/recommendations
```

But other apis can't work, like `/api/footprint` and `api/emissions`. Returned error like below:
```[1] 2021-11-02T10:13:24.802Z [api] info: Regions emissions factors API request started
[1] 2021-11-02T10:13:49.593Z [api] error: Unable to process footprint request.TypeError: Cannot read property 'kilowattHours' of undefined
[1]     at /Users/mattcui/myspace/src/klarity-ccf/node_modules/@cloud-carbon-footprint/core/src/CloudProviderAccount.ts:70:41
[1]     at Array.map (<anonymous>)
[1]     at /Users/mattcui/myspace/src/klarity-ccf/node_modules/@cloud-carbon-footprint/core/src/CloudProviderAccount.ts:60:11
[1]     at Array.map (<anonymous>)
[1]     at AWSAccount.<anonymous> (/Users/mattcui/myspace/src/klarity-ccf/node_modules/@cloud-carbon-footprint/core/src/CloudProviderAccount.ts:28:75)
[1]     at step (/Users/mattcui/myspace/src/klarity-ccf/node_modules/@cloud-carbon-footprint/core/dist/CloudProviderAccount.js:33:23)
[1]     at Object.next (/Users/mattcui/myspace/src/klarity-ccf/node_modules/@cloud-carbon-footprint/core/dist/CloudProviderAccount.js:14:53)
[1]     at fulfilled (/Users/mattcui/myspace/src/klarity-ccf/node_modules/@cloud-carbon-footprint/core/dist/CloudProviderAccount.js:5:58)
[1]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

And end up with Out-of-memory. Looks that it still tried to get the data from local cache rather than calling api to cost explorer or metrics.

### To Reproduce

Just follow the doc to yarn start the application, and modified .env file to fit to your AWS environment.

### Additional Information

© 2021 Thoughtworks, Inc.

**Comment by dtoakley** [comment]
Hey @mattcui -- I've believe that we have implemented a fix for this. Could you pull the latest code from the `trunk` branch and try again, and let us know how it goes?

**Comment by 4upz** [comment]
Hi @mattcui , looks like we implemented a fix for this so we're closing this issue.
